title: "Sepehr's CV"
description: "Showcasing my abilities, projects, and resume."
author:
  name: "Sepehr Nazeri"
  email: "sepehr.nazeri1999@gmail.com"
  url: "https://sepehrnazeri.github.io"
social:
  github: "SepehrNazeri"
  linkedin: "https://www.linkedin.com/in/sepehr-nazeri/"
